### ISSUE TITLE
Show decimal values for difficulty in map embeds

### ISSUE THREAD

**Issue by tilda** [AxerBot/axer-bot#169]
![image](https://user-images.githubusercontent.com/8301262/179564714-d3fcfa0e-7762-47bd-89db-1f500390ea8c.png)
For reference, I am talking about the 4 statistics underlined in the image above. I don't think it makes sense to round the values up in most contexts - considering stuff like SR (and skill SR) isn't rounded up like this.

**Comment by Hiviexd** [comment]
agree, either me or sebola will look into it soon

**Comment by Sebola3461** [comment]
oh, ill look this later

**Comment by Sebola3461** [comment]
its fixed
