### ISSUE TITLE
Finalize slash command migration

### ISSUE THREAD

**Issue by Hiviexd** [AxerBot/axer-bot#208]
most commands are on slash and we already have a solid codebase for slash, making this issue mainly to track legacy commands

## priority: high
- [ ] help
- [ ] quotes
- [ ] cooldown (will probably be deprecated in favor of a system that toggles `ephemeral` for commands)
- [ ] logging

## priority: low
- [ ] dev category
- [ ] contests category

**Comment by Sebola3461** [comment]
did :3
