### ISSUE TITLE
add !reminder command

### ISSUE THREAD

**Issue by Hiviexd** [AxerBot/axer-bot#41]
a command that makes the bot ping you with a specified message after x amount of time 

## Command:
`!reminder 12h get some maidens` Bot will ping you after 12 hours with the phrase "@user get some maidens"
`!reminder cancel` to cancel your latest reminder

bot can take minutes (4m), hours (6h) and days (8d) as times

**Comment by Sebola3461** [comment]
eu sexo

**Comment by Hiviexd** [comment]
need that db magic
